browser:
  browser_name: 'chromium'
  headless: false
  slow_mo: 50
  downloads_path: null
context:
  ignore_https_errors: true
  java_script_enabled: true
  bypass_csp: true
  viewport:
    width: 1470
    height: 715
  locale: 'zh-CN'
  extra_http_headers: null
  timezone_id: 'Asia/Shanghai'
env: '${UI_TEST_ENV}'
hook: 'common/hook.py'
tests: '${UI_TEST_CASES}'
users:


# App测试配置（Airtest）
app:
  package: 'com.wilmar.sfa'
  activity: 'crc646448c55d263b93b4.MainActivity'
  device: '127.0.0.1:5555'  # MuMu模拟器
