
from fasttest import TestCase, driver
from common import login, window

class TestCase(TestCase):

    def test_DMS_ORDER_LIST(self):
        """
        tc-p0: DMS创建采购计划
        """
        window.web_window()
        login.login_dms_plus()
        driver.click('采购管理')
        driver.click('采购计划')
        driver.sleep(3)
        driver.click('class=el-button el-icon-plus el-button--primary')
        driver.sleep(5)
        driver.click('placeholder=请选择')
        driver.click('总部/丰厨(上海)供应链管理有限公司')
        driver.sleep(1)
        driver.click('placeholder=请选择', index=1)
        driver.click('郫都区清伦粮油经营部')
        driver.sleep(2)
        driver.click('placeholder=请选择', index=2)
        driver.sleep(1)
        driver.click('仅供货')
        driver.sleep(1)
        driver.click('placeholder=请选择供应商计划交期')
        driver.sleep(2)
        driver.input('2028-03-30 19:52:58')
        driver.click(' 确定 ')
        driver.click('placeholder=请选择', index=3)
        driver.sleep(1)
        driver.click('丰厨仓')
        driver.click('class=el-button el-icon-plus el-button--primary')
        driver.sleep(1)
        driver.click('请选择产品名称')
        driver.sleep(1)
        driver.click('class=el-select__caret el-input__icon el-icon-', index=5)
        driver.sleep(1)
        driver.click('金龙鱼餐饮专用菜籽油10L*2(非转基因)')
        driver.sleep(1)
        driver.click('0', index=1)
        driver.sleep(1)
        driver.click('placeholder=采购计划数量')
        driver.input(text="10", clear=True)
        driver.click('class=vxe-cell c--tooltip', index=2)
        driver.input(text="10", clear=True)
        driver.sleep(2)
        driver.click('placeholder=请选择', index=6)
        driver.click('class=form-detail-block')
        driver.click('placeholder=请选择', index=6)
        driver.sleep(1)
        driver.input(text="10", clear=True)
        driver.sleep(1)
        driver.click('确定')